INSERT INTO LESSORS(ID, FIRST_NAME, LAST_NAME) VALUES (1, 'John', 'Lessor');
INSERT INTO LESSEES(ID, FIRST_NAME, LAST_NAME) VALUES (1, 'Richard', 'Lessee');
INSERT INTO PLACES(ID, NAME, AREA, UNIT_PRICE) VALUES (1, 'House', 1, 1);